// COMPARISON OPERATORS 
//  They are operators used to compare 2 values
//  They always return a Boolean (True or False)

// 1. Equal to (==)
// Checks if 2 values are equal 
// Ignores the type

// console.log(" Using numbers ->" , 5 == 5)
// console.log(" Using strings ->" , 5 == "5")


// 2. Strictly Equal to (===)
// Check if values are equal and of the same type


// console.log(" Using numbers ->" , 5 === 5)
// console.log(" Using strings ->" , 5 === "5")




// 3.Not Equal to (!=)
// Checks if 2 values are not equal
// Ignores the type

// console.log(" Using numbers ->" , 5 != 5)
// console.log(" Using strings ->" , 5 != "5")


// 4.Strictly Not Equal to (!==)
// Checks if values are not equal
// Checks the type

// console.log(" Using numbers ->" , 5 !== 5)
// console.log(" Using strings ->" , 5 !== "5")


// 5.Greater than (>)

// Checks if the left value is greater than the right



// console.log(" Using numbers ->" , 15 > 6)
// console.log(" Using strings ->" , 5 > "100")


// 6.Less than (<)
// Checks if the left value is less than the right

// console.log(" Using numbers ->" , 15 < 6)
// console.log(" Using strings ->" , 5 < "100")


// 7.Greater than or equal to (>=)

// Returns True if the left value is greater than or exactly equal to the right value

// console.log(" Using numbers ->" , 15 >= 6)
// console.log(" Using strings ->" , "209" >= 210)

// 8.Less than or equal to (<=)
// Returns True if the left value is less than or exactly equal to the right value

// console.log(" Using numbers ->" , 15 <= 6)
// console.log(" Using strings ->" , "309" <= 113)

// Question

/*

You are given the following Values

let studentName = "    brian     ";
let mathScore = 78.456;
let englishScore = 65;

Required :
1. Use the string methods to remove the spaces and capitalize the name
2. Use number methods to round the math score to 2 decimal places 
3. Use arithmetic operators to find the average of both scores
4. Use a comparison operator to check if the average is greater than or equal to 70
5. Use console.log to display both the average and whether the student passed or not ,using 
the comparison result.


Note - Show the steps that you have followed

Expected Result

student:Brian
Average Score:78.46
passed:true or false





*/