// COMPARISON OPERATORS 
//  They are operators used to compare 2 values
//  They always return a Boolean (True or False)

// 1. Equal to (==)
// Checks if 2 values are equal 
// Ignores the type

// console.log(" Using numbers ->" , 5 == 5)
// console.log(" Using strings ->" , 5 == "5")


// 2. Strictly Equal to (===)
// Check if values are equal and of the same type


// console.log(" Using numbers ->" , 5 === 5)
// console.log(" Using strings ->" , 5 === "5")




// 3.Not Equal to (!=)
// Checks if 2 values are not equal
// Ignores the type

// console.log(" Using numbers ->" , 5 != 5)
// console.log(" Using strings ->" , 5 != "5")


// 4.Strictly Not Equal to (!==)
// Checks if values are not equal
// Checks the type

// console.log(" Using numbers ->" , 5 !== 5)
// console.log(" Using strings ->" , 5 !== "5")


// 5.Greater than (>)

// Checks if the left value is greater than the right



// console.log(" Using numbers ->" , 15 > 6)
// console.log(" Using strings ->" , 5 > "100")


// 6.Less than (<)
// Checks if the left value is less than the right

// console.log(" Using numbers ->" , 15 < 6)
// console.log(" Using strings ->" , 5 < "100")


// 7.Greater than or equal to (>=)

// Returns True if the left value is greater than or exactly equal to the right value

// console.log(" Using numbers ->" , 15 >= 6)
// console.log(" Using strings ->" , "209" >= 210)

// 8.Less than or equal to (<=)
// Returns True if the left value is less than or exactly equal to the right value

console.log(" Using numbers ->" , 15 <= 6)
console.log(" Using strings ->" , "309" <= 113)